Avoid unnecessary copies by passing some parameters by reference
NEstelami/ZAPD pull request #46
Opened 2021-01-04 18:15 UTC by leoetlino

Pass some parameters by reference to avoid unnecessary copies.

When the parameter is intended to be copied into a member variable,
pass it by value and move it into the member instead.

This doesn't fix every occurrence of the issue but this diff is already
getting big so let's stop here for the moment.

2021-01-04 23:17 UTC, Kenix3 requested changes
The changes in general look good to me, but it looks like we duplicated some changes.

Additionally, ZAPD compiled with this branches changes does not build an OOT ROM.

```
kenix@DESKTOP-R69G3L5:/mnt/d/Zelda/oot$ make
python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL1' undefined; reoccurrences will not be reported.
 static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
 --------------------------^
cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL2' undefined; reoccurrences will not be reported.
 static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
 ----------------------------------------^
cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL3' undefined; reoccurrences will not be reported.
 static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
 ------------------------------------------------------^
cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL4' undefined; reoccurrences will not be reported.
 static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
 --------------------------------------------------------------------^
cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL5' undefined; reoccurrences will not be reported.
 static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
 ----------------------------------------------------------------------------------^
cfe: Warning 709: /tmp/preprocessed3liw8vsn.c, line 102: Incompatible pointer type assignment
         DynaPolyInfo_SetActorMove(thisx, 0);
 ----------------------------------^
cfe: Error: /tmp/preprocessed3liw8vsn.c, line 178: 'gBgSpot09DL6' undefined; reoccurrences will not be reported.
         do {{                                                                          Gfx *_g = (Gfx *)(__gfxCtx->polyXlu.p++);
        _g->words.w0 = (((u32) (((u32)((0xde)) & ((0x01 << ( 8)) - 1)) << ( 24))) | ((u32) (((u32)((0x00)) & ((0x01 << ( 8)) - 1)) << ( 16))) |                         ((u32) (((u32)((0)) & ((0x01 << ( 16)) - 1)) << ( 0))));
                _g->words.w1 = (unsigned int)( gBgSpot09DL6);                           }} while (0)   ;
 -------------                                                                          -----------------------------------------
        ---------------------------------------------------------------------------------------------------------------------------------------                         --------------------------------------------------------
                -------------------------------^
Failed to compile file src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c. Command line:

tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /mnt/d/Zelda/oot/src/overlays/actors/ovl_Bg_Spot09_Obj -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o /tmp/preprocessed3liw8vsn.c

make: *** [Makefile:224: build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o] Error 55
```

2021-01-04 23:35 UTC, NEstelami commented
> The changes in general look good to me, but it looks like we duplicated some changes.
> 
> Additionally, ZAPD compiled with this branches changes does not build an OOT ROM.
> 
> ```
> kenix@DESKTOP-R69G3L5:/mnt/d/Zelda/oot$ make
> python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
> cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL1' undefined; reoccurrences will not be reported.
>  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
>  --------------------------^
> cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL2' undefined; reoccurrences will not be reported.
>  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
>  ----------------------------------------^
> cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL3' undefined; reoccurrences will not be reported.
>  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
>  ------------------------------------------------------^
> cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL4' undefined; reoccurrences will not be reported.
>  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
>  --------------------------------------------------------------------^
> cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL5' undefined; reoccurrences will not be reported.
>  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
>  ----------------------------------------------------------------------------------^
> cfe: Warning 709: /tmp/preprocessed3liw8vsn.c, line 102: Incompatible pointer type assignment
>          DynaPolyInfo_SetActorMove(thisx, 0);
>  ----------------------------------^
> cfe: Error: /tmp/preprocessed3liw8vsn.c, line 178: 'gBgSpot09DL6' undefined; reoccurrences will not be reported.
>          do {{                                                                          Gfx *_g = (Gfx *)(__gfxCtx->polyXlu.p++);
>         _g->words.w0 = (((u32) (((u32)((0xde)) & ((0x01 << ( 8)) - 1)) << ( 24))) | ((u32) (((u32)((0x00)) & ((0x01 << ( 8)) - 1)) << ( 16))) |                         ((u32) (((u32)((0)) & ((0x01 << ( 16)) - 1)) << ( 0))));
>                 _g->words.w1 = (unsigned int)( gBgSpot09DL6);                           }} while (0)   ;
>  -------------                                                                          -----------------------------------------
>         ---------------------------------------------------------------------------------------------------------------------------------------                         --------------------------------------------------------
>                 -------------------------------^
> Failed to compile file src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c. Command line:
> 
> tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /mnt/d/Zelda/oot/src/overlays/actors/ovl_Bg_Spot09_Obj -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o /tmp/preprocessed3liw8vsn.c
> 
> make: *** [Makefile:224: build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o] Error 55
> ```

The error you're getting is because of outdated XMLs, it looks like. I'm pretty sure gBgSpot09DL1-6 got renamed.

2021-01-04 23:39 UTC, Kenix3 commented
> 
> 
> > The changes in general look good to me, but it looks like we duplicated some changes.
> > Additionally, ZAPD compiled with this branches changes does not build an OOT ROM.
> > ```
> > kenix@DESKTOP-R69G3L5:/mnt/d/Zelda/oot$ make
> > python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL1' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  --------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL2' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  ----------------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL3' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  ------------------------------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL4' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  --------------------------------------------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL5' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  ----------------------------------------------------------------------------------^
> > cfe: Warning 709: /tmp/preprocessed3liw8vsn.c, line 102: Incompatible pointer type assignment
> >          DynaPolyInfo_SetActorMove(thisx, 0);
> >  ----------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 178: 'gBgSpot09DL6' undefined; reoccurrences will not be reported.
> >          do {{                                                                          Gfx *_g = (Gfx *)(__gfxCtx->polyXlu.p++);
> >         _g->words.w0 = (((u32) (((u32)((0xde)) & ((0x01 << ( 8)) - 1)) << ( 24))) | ((u32) (((u32)((0x00)) & ((0x01 << ( 8)) - 1)) << ( 16))) |                         ((u32) (((u32)((0)) & ((0x01 << ( 16)) - 1)) << ( 0))));
> >                 _g->words.w1 = (unsigned int)( gBgSpot09DL6);                           }} while (0)   ;
> >  -------------                                                                          -----------------------------------------
> >         ---------------------------------------------------------------------------------------------------------------------------------------                         --------------------------------------------------------
> >                 -------------------------------^
> > Failed to compile file src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c. Command line:
> > 
> > tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /mnt/d/Zelda/oot/src/overlays/actors/ovl_Bg_Spot09_Obj -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o /tmp/preprocessed3liw8vsn.c
> > 
> > make: *** [Makefile:224: build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o] Error 55
> > ```
> 
> The error you're getting is because of outdated XMLs, it looks like. I'm pretty sure gBgSpot09DL1-6 got renamed.

Interesting. I built on the most recent upstream/master of OOT. 🤔

2021-01-04 23:49 UTC, Kenix3 commented
> 
> 
> > The changes in general look good to me, but it looks like we duplicated some changes.
> > Additionally, ZAPD compiled with this branches changes does not build an OOT ROM.
> > ```
> > kenix@DESKTOP-R69G3L5:/mnt/d/Zelda/oot$ make
> > python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL1' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  --------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL2' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  ----------------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL3' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  ------------------------------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL4' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  --------------------------------------------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 55: 'gBgSpot09DL5' undefined; reoccurrences will not be reported.
> >  static Gfx* sDLists[] = { gBgSpot09DL1, gBgSpot09DL2, gBgSpot09DL3, gBgSpot09DL4, gBgSpot09DL5 };
> >  ----------------------------------------------------------------------------------^
> > cfe: Warning 709: /tmp/preprocessed3liw8vsn.c, line 102: Incompatible pointer type assignment
> >          DynaPolyInfo_SetActorMove(thisx, 0);
> >  ----------------------------------^
> > cfe: Error: /tmp/preprocessed3liw8vsn.c, line 178: 'gBgSpot09DL6' undefined; reoccurrences will not be reported.
> >          do {{                                                                          Gfx *_g = (Gfx *)(__gfxCtx->polyXlu.p++);
> >         _g->words.w0 = (((u32) (((u32)((0xde)) & ((0x01 << ( 8)) - 1)) << ( 24))) | ((u32) (((u32)((0x00)) & ((0x01 << ( 8)) - 1)) << ( 16))) |                         ((u32) (((u32)((0)) & ((0x01 << ( 16)) - 1)) << ( 0))));
> >                 _g->words.w1 = (unsigned int)( gBgSpot09DL6);                           }} while (0)   ;
> >  -------------                                                                          -----------------------------------------
> >         ---------------------------------------------------------------------------------------------------------------------------------------                         --------------------------------------------------------
> >                 -------------------------------^
> > Failed to compile file src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c. Command line:
> > 
> > tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /mnt/d/Zelda/oot/src/overlays/actors/ovl_Bg_Spot09_Obj -o build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o /tmp/preprocessed3liw8vsn.c
> > 
> > make: *** [Makefile:224: build/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o] Error 55
> > ```
> 
> The error you're getting is because of outdated XMLs, it looks like. I'm pretty sure gBgSpot09DL1-6 got renamed.

I built OOT with leo's changes again.
```
make clean && make -j
```
on ZAPD

then I ensured OOT is on most recent upstream/master
```
make clean
./extract_assets.py
make -j
```
on OOT and encountered the same error

2021-01-05 01:26 UTC, leoetlino commented
The errors should be fixed now

```
f0b7f35375f9cc8ca1b2d59d78e35405  zelda_ocarina_mq_dbg.z64
zelda_ocarina_mq_dbg.z64: OK
```

2021-01-05 01:32 UTC, Kenix3 approved these changes

2021-01-05 01:33 UTC, Kenix3 commented
Looks good to me. OOT build is now OK.

2021-01-05 11:31 UTC, leoetlino commented
rebased and still builds OK

2021-01-05 21:28 UTC, merged